### ISSUE TITLE
duplicate message

### ISSUE THREAD

**Issue by catrinque** [unkbot/chatwoot-codechat#21]
**Describe the bug**
First, thank you for your work, it helps a lot of people, congratulations.

The problem is the following: when I answer the customer by cell phone instead of chatwoot, the message is duplicated.

**To Reproduce**
example: I type "hi" and then "hi" arrives at the client and then "operator: hi"

**Expected behavior**
this error didn't happen before

![erro](https://github.com/unkbot/chatwoot-codechat/assets/138030797/b14171b3-618b-4f6e-abf1-eef4dedc15fd)

**Comment by mtcoliveira** [comment]
Same problem

**Comment by catrinque** [comment]
> Seu problema deve estar relacionado à variável `IMPORT MESSAGES SENT`deve ser definida como `true`. Verifique isso e veja se resolve o seu problema.

Bom dia! sim esta como true, antes não acontecia de duplicar, ele apenas pegava todas as conversas, sem duplicar, ele fazia um espelho do celular.

**Comment by hugovrcandido** [comment]
Bom dia! 
Mesmo problema aqui.

**Comment by muriloorama** [comment]
Same problem

**Comment by w3nder** [comment]
no .env
IMPORT_MESSAGES_SENT=false

https://github.com/code-chat-br/whatsapp-api/blob/main/src/dev-env.yml#L86

Aqui você pode colocar como false também é quando você envia uma mensagem ela não é enviada no webhook é o conector não vai processar

**Comment by hugovrcandido** [comment]
@w3nder, agradeço o retorno.

Fiz o teste, mas agora as mensagens enviadas pelo celular do cliente não chegam ao chatwoot e no log do container, apresenta o seguinte erro:

`
🎉 Evento recebido de WSAPI
SqliteError: no such table: providers
    at Database.prepare (/app/node_modules/better-sqlite3/lib/methods/wrappers.js:5:21)
    at eventCodeChat (/app/events/index.js:105:40)
    at /app/app.js:44:55
    at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
    at next (/app/node_modules/express/lib/router/route.js:144:13)
    at Route.dispatch (/app/node_modules/express/lib/router/route.js:114:3)
    at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
    at /app/node_modules/express/lib/router/index.js:284:15
    at param (/app/node_modules/express/lib/router/index.js:365:14)
    at param (/app/node_modules/express/lib/router/index.js:376:14) {
  code: 'SQLITE_ERROR'
}
`

-> As mensagens enviadas pelo chatwoot chegam normalmente;
-> As mensagens enviadas pelo cliente não chegam;
-> Mensagens enviadas pelo celular ao cliente, não aparecem no chatwoot; (IMPORT_MESSAGES_SENT=false)

Não há uma forma de mesmo que a mensagem seja enviada pelo celular ou chatwoot, ela não seja duplicada?

**Comment by MangaSinix** [comment]
Opa Pelo o que eu vi no log do pm2 acontece o seguinte
A mensagem enviada pelo whatsapp web chega no chatwoot, o chatwoot recebe a mensagem e dispara ela novamente, na teoria deveria ter uma condição para caso que a mensagem saia pelo whatsapp ela chegue  no chatwoot mas não se dispare sozinha

**Comment by w3nder** [comment]
Estou trabalhando em uma nova versão que até quarta já estará disponível aqui. 
Devido algumas mudança o código ficou difícil de dar manutenção é resolvi reescrever ele. 

Sobre mensagem duplicada eu irei ver como irei resolver essa situação.
Pois como eu recebo o evento novamente a mensagem e reenviada, e se eu impedir as mensagem que foi envida do dispositivo ou página web não vai ser entregue no chatwoot. 

Peço desculpa a todos pelos os problema que foi encontrado e devido ao meu tempo está bem curto não teve como eu dar um carinho especial para o conector.

**Comment by francisbreit** [comment]
nsagem saia pelo whatsapp ela chegue no chatwoot mas não se dispare sozinha


> Estou trabalhando em uma nova versão que até quarta já estará disponível aqui. Devido algumas mudança o código ficou difícil de dar manutenção é resolvi reescrever ele.
> 
> Sobre mensagem duplicada eu irei ver como irei resolver essa situação. Pois como eu recebo o evento novamente a mensagem e reenviada, e se eu impedir as mensagem que foi envida do dispositivo ou página web não vai ser entregue no chatwoot.
> 
> Peço desculpa a todos pelos os problema que foi encontrado e devido ao meu tempo está bem curto não teve como eu dar um carinho especial para o conector.

Seu projeto é muito bom!!! Essa questão da mensagem duplicada foi onde chegou-se a um dilema, pelo que vi. Mas será que não existe uma varável a qual possa ser usada como fonte origem... Assim, seria possível, quando o evento chega no chatwoot e o mesmo não corresponder ao dispositivo ou WhatsApp Web,  o chatwoot nao dispararia....

**Comment by francisbreit** [comment]
> @w3nder, agradeço o retorno.
> 
> Fiz o teste, mas agora as mensagens enviadas pelo celular do cliente não chegam ao chatwoot e no log do container, apresenta o seguinte erro:
> 
> > 🎉 Evento recebido de WSAPI
> > SqliteError: no such table: providers
> > at Database.prepare (/app/node_modules/better-sqlite3/lib/methods/wrappers.js:5:21)
> > at eventCodeChat (/app/events/index.js:105:40)
> > at /app/app.js:44:55
> > at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
> > at next (/app/node_modules/express/lib/router/route.js:144:13)
> > at Route.dispatch (/app/node_modules/express/lib/router/route.js:114:3)
> > at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
> > at /app/node_modules/express/lib/router/index.js:284:15
> > at param (/app/node_modules/express/lib/router/index.js:365:14)
> > at param (/app/node_modules/express/lib/router/index.js:376:14) {
> > code: 'SQLITE_ERROR'
> > }
> 
> -> As mensagens enviadas pelo chatwoot chegam normalmente; -> As mensagens enviadas pelo cliente não chegam; -> Mensagens enviadas pelo celular ao cliente, não aparecem no chatwoot; (IMPORT_MESSAGES_SENT=false)
> 
> Não há uma forma de mesmo que a mensagem seja enviada pelo celular ou chatwoot, ela não seja duplicada?

Parece que o @w3nder está revendo o código... Estou usando essa última versão do conector e ela está bem interssante, pois envia e receb os anexos (apenas o pdf com comentário não chega) .. No caso das mensagens duplicadas a solução provisória seria configurar (IMPORT_MESSAGES_SENT=false) e pedir para os agentes das respectivas caixas de entrada nao responderem pelo celular e sim pelo chatwoot... pelo menos até resolver o problema...

**Comment by MangaSinix** [comment]
Alguem sabe se foi corrigido?

**Comment by A-juniorl** [comment]
Alguém sabe de alguma atualização sobre o problema?

**Comment by hereck** [comment]
Estamos aqui com o mesmo problema. Aguardando novidades.

**Comment by NLSARCOS** [comment]
Qualquer atualização?  Por favor nos ajude

**Comment by dollyzn** [comment]
boa noite pessoal, tava aqui na madrugada sem nada pra fazer e vim verificar a issue, vou fazer um pull request com a correção necessária

**Comment by dollyzn** [comment]
> @w3nder, agradeço o retorno.
> 
> Fiz o teste, mas agora as mensagens enviadas pelo celular do cliente não chegam ao chatwoot e no log do container, apresenta o seguinte erro:
> 
> > 🎉 Evento recebido de WSAPI
> > SqliteError: no such table: providers
> > at Database.prepare (/app/node_modules/better-sqlite3/lib/methods/wrappers.js:5:21)
> > at eventCodeChat (/app/events/index.js:105:40)
> > at /app/app.js:44:55
> > at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
> > at next (/app/node_modules/express/lib/router/route.js:144:13)
> > at Route.dispatch (/app/node_modules/express/lib/router/route.js:114:3)
> > at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
> > at /app/node_modules/express/lib/router/index.js:284:15
> > at param (/app/node_modules/express/lib/router/index.js:365:14)
> > at param (/app/node_modules/express/lib/router/index.js:376:14) {
> > code: 'SQLITE_ERROR'
> > }
> 
> -> As mensagens enviadas pelo chatwoot chegam normalmente; -> As mensagens enviadas pelo cliente não chegam; -> Mensagens enviadas pelo celular ao cliente, não aparecem no chatwoot; (IMPORT_MESSAGES_SENT=false)
> 
> Não há uma forma de mesmo que a mensagem seja enviada pelo celular ou chatwoot, ela não seja duplicada?

recomendo vc excluir o db.sqlite, atualizar o repositorio buildar e dar o comando iniciar novamente na instancia

**Comment by hereck** [comment]
Aqui fiz a atualização mas o problema persiste, precisamos fazer algo diferente?

**Comment by dollyzn** [comment]
> 

vc apagou a pasta dist e buildou novamente a aplicação?
